apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kapilkhubchandani
  name: kapilkhubchandani
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kapilkhubchandani
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kapilkhubchandani
    spec:
      containers:
      - image: acrkhubchandani.azurecr.io/kapilkhubchandani:51d8d951f979731152119634e45d4d28d7a5161c
        name: kapilkhubchandani
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 80
           protocol: TCP
           name: http
        env:
         - name: ASPNETCORE_URLS
           value: http://+:80         
        resources: {}
status: {}
