apiVersion: v1
kind: Service
metadata:
  name: kapilkhubchandani
  labels:
    app: kapilkhubchandani
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: htp
      protocol: TCP
  selector:
    app: kapilkhubchandani
 