apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kapilkhubchandani
  name: {{.Release.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: kapilkhubchandani
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kapilkhubchandani
    spec:
      containers:
      - image: {{.Values.image.name}}:{{.Values.image.tag}}
        name: kapilkhubchandani
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 80
           protocol: TCP
           name: http
        env:
         - name: ASPNETCORE_URLS
           value: http://+:80         
        resources: {}
status: {}
