apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
spec:
  provider: azure
  parameters:
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
            objectName: TestKey
            objectType: secret      # object types: secret, key or cert
    keyvaultName: AKSKeyVault18148449156
    useVMManagedIdentity: "false"
    tenantId: b2bf46f0-438c-4409-a267-ca444339c186
    usePodIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: kapilkhubchandaniorg
    subscriptionId: 3e4e586a-a0ff-49db-bb07-e8cb8fa5601a
metadata:
  name: azure-kv-provider
kind: SecretProviderClass

