apiVersion: v1 
kind: Service 
metadata: 
  name: mssql 
  namespace: my-profile
  labels:
   app: mssql 
spec: 
  clusterIP: None
  selector: 
    app: mssql 
  ports: 
    - protocol: TCP 
      port: 1433 
      targetPort: 1433 
  