apiVersion: v1
kind: Service
metadata:
  labels:
    app: mssql
  name: mssql
  namespace: my-profile
spec:
  clusterIP: None
  ports:
  - name: database-port
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: mssql

