name: Container Workflow
on: 
  workflow_dispatch:
  
env:
  ACR_LOGON_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/kapilkhubchandani:${{ github.sha }}

jobs:
  build-deploy-image:
    runs-on: ubuntu-latest
    steps:
      #checkout the repo
      - name: Checkout Github Action
        uses: actions/checkout@v4.1.0

      - name: Build and push image
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGON_SERVER }}
          username: ${{secrets.SERVICE_PRINCIPAL_ID}}
          password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
